default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password:

development:
  <<: *default
  database: correntedaciencia_development

test:
  <<: *default
  database: correntedaciencia_test

production:
  <<: *default
  database: correntedaciencia_production
